ARG BASE_IMAGE_TAG="21-jdk-alpine"
FROM eclipse-temurin:${BASE_IMAGE_TAG}

LABEL maintainer="info@redmic.es"

ARG DIRPATH \
	DEFAULT_JAVA_OPTS \
	LOG_LEVEL

ENV DEFAULT_JAVA_OPTS="${DEFAULT_JAVA_OPTS}" \
	LOG_LEVEL="${LOG_LEVEL}"

WORKDIR "${DIRPATH}"

ENTRYPOINT java ${DEFAULT_JAVA_OPTS} ${JAVA_OPTS} -jar "${MICROSERVICE_NAME}.jar"
